{
	"version": 1502150484,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/astronauta-sheet0.png",
		"images/astronauta-sheet1.png",
		"images/astronauta-sheet2.png",
		"images/planeta1-sheet0.png",
		"images/planeta2-sheet0.png",
		"images/planeta3-sheet0.png",
		"images/colisorchaoceu-sheet0.png",
		"images/estrela-sheet0.png",
		"images/criaobjetos-sheet0.png",
		"images/vidavazio-sheet0.png",
		"images/vidacheio-sheet0.png",
		"images/meteorofogo-sheet0.png",
		"images/meteorofogo-sheet1.png",
		"images/criarmeteoros-sheet0.png",
		"images/et-sheet0.png",
		"images/et-sheet1.png",
		"images/meteorosemfogo-sheet0.png",
		"images/background-sheet0.png",
		"images/botaoplay-sheet0.png",
		"images/botaofechar-sheet0.png",
		"images/quadropausa-sheet0.png",
		"images/botaopausa-sheet0.png",
		"images/botaopulo-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/tiledbackground.png",
		"images/txt.png",
		"images/particles.png",
		"images/logoadelirogames-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/pfechado-sheet0.png",
		"images/paberto-sheet0.png",
		"images/txt1-sheet0.png",
		"images/txt2-sheet0.png",
		"images/txt3-sheet0.png",
		"images/txtcreditos-sheet0.png",
		"images/sensorcreditos-sheet0.png",
		"media/fundo 2.m4a",
		"media/fundo 2.ogg",
		"media/fundo 4.m4a",
		"media/fundo 4.ogg",
		"media/colisao.m4a",
		"media/colisao.ogg",
		"media/dano.m4a",
		"media/dano.ogg",
		"media/estrela.m4a",
		"media/estrela.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}